export const TYPE_FILE = 'fieldType/FILE'
export const TYPE_DATE = 'fieldType/DATE'
export const TYPE_RADIO = 'fieldType/RADIO'
export const TYPE_SELECT = 'fieldType/SELECT'
export const TYPE_SCHEMAS = 'fieldType/SCHEMAS'
export const TYPE_ORG_UNIT = 'fieldType/ORG_UNIT'
export const TYPE_ORG_UNIT_SINGLE_SELECT = 'fieldType/ORG_UNIT_SINGLE_SELECT'
export const TYPE_MORE_OPTIONS = 'fieldType/MORE_OPTIONS'
export const TYPE_DATASET_PICKER = 'fieldType/DATASET_PICKER'

export const CTX_DEFAULT = 'ctx/DEFAULT'
export const CTX_MORE_OPTIONS = 'ctx/MORE_OPTIONS'
export const CTX_CSV_OPTION = 'ctx/CSV_OPTION'
